### ISSUE TITLE
code release

### ISSUE THREAD

**Issue by yyvhang** [guochengqian/Pix4Point#1]
Hi, glad to see the interesting work. Would you like to release the code and the pre-trained model?
If so, when?

**Comment by guochengqian** [comment]
working hard to release in two weeks

**Comment by Cemm23333** [comment]
how to release pretrained model？

**Comment by Cemm23333** [comment]
When to release the pretrained model?

**Comment by guochengqian** [comment]
paper is rejected. so, no plan for releasing pretrained model for now. you can easily train by your self. code is available.
